project_id = "xkwdfddamvuhucorwttw"
// supabase/config.toml
[cors]
enabled = true
allowed_origins = [
  "http://localhost:3000",
  "https://yourdomain.com"
]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["*"]
exposed_headers = []
max_age = 600
credentials = true